name: Docker Image CI

env:
  IMAGE_TAG: ${{ (date +%s) }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login with Github Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/baesky/dldev:$IMAGE_TAG
        docker push ghcr.io/baesky/dldev:$IMAGE_TAG
