name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: specify a tag for new image
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login with Github Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/baesky/dldev:${{ github.events.inputs.image_tag }}
        docker push ghcr.io/baesky/dldev:$${{ github.events.inputs.image_tag }}
