name: ci

on:
  push:
    branches:
      - "main"

jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Checkout
uses: docker/login-action@v2
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the DLDev Docker image
run: |
      docker build . --tag ghcr.io/baesky/DLDev:latest
      docker push ghcr.io/baesky/DLDev:latest
    
